### ISSUE TITLE
Request improvements

### ISSUE THREAD

**Issue by MaxFlower** [lzanchin/odin-calculator#1]
I have done with reviewing the `odin-calculator` js implementation 💻  
To resume, the main script is well-structured and has good readability. Aside from few inaccuracy in rounded calculations (1/999 = 0), the rest cases are covered presicely.  Well done 👏🏻  

I would point a few things out that can be improved:

- switch to strict equality in order to follow the best practices [line 21](https://github.com/lzanchin/odin-calculator/blob/main/script.js#L21). More [details here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality)

- avoid repetitions like on [lines 25-25](https://github.com/lzanchin/odin-calculator/blob/main/script.js#L25-L29) by using constants or array of constants.
For example,`const allOperations = ['+',  '-', '*', '/'];` then it is not a problem use condition like this `allOperations.includes(value);`
Another case when instead of `value == "+" || value == "-" || value == "/" || value == "*"` can be use just `allOperations.any(operation=> operation=== value)`

- be accurate with the chain of if's conditions [line 86-102](https://github.com/lzanchin/odin-calculator/blob/main/script.js#L86-102). More details [here](https://stackoverflow.com/questions/43934388/how-to-make-javascript-exclude-some-mentioned-variables)

- [PRO] the app perfomance is sensitive to number of listeners and every developer should follow the rule: 'the less listeners, the better perfomance'. On [line L9-L13](https://github.com/lzanchin/odin-calculator/blob/main/script.js#L9-L13) the code can be enchanced in [bubbling way](https://javascript.info/bubbling-and-capturing) :balloon: which implies to add one listener on the parent element instead of plenty listeners on each of child.

**Comment by MaxFlower** [comment]
And as a bug, I would mention this behavior:
The operation sign is still displayed even the result is computed (see screenshot).
Steps to reproduce:
`14` `-` `3` `=` output:  `11-`

<img width="420" alt="Screen Shot 2023-02-27 at 9 44 06 am" src="https://user-images.githubusercontent.com/10515741/221445094-1cf67ad0-149b-4ce7-bc10-0735b2400573.png">

Expect:
The operation sign shouldn't be displayed at the end after computing
`14` `-` `3` `=` output:  `11`

**Comment by lzanchin** [comment]
> I have done with reviewing the `odin-calculator` js implementation 💻 To resume, the main script is well-structured and has good readability. Aside from few inaccuracy in rounded calculations (1/999 = 0), the rest cases are covered presicely. Well done 👏🏻
> 
> I would point a few things out that can be improved:
> 
> * switch to strict equality in order to follow the best practices [line 21](https://github.com/lzanchin/odin-calculator/blob/main/script.js#L21). More [details here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality)
> * avoid repetitions like on [lines 25-25](https://github.com/lzanchin/odin-calculator/blob/main/script.js#L25-L29) by using constants or array of constants.
>   For example,`const allOperations = ['+',  '-', '*', '/'];` then it is not a problem use condition like this `allOperations.includes(value);`
>   Another case when instead of `value == "+" || value == "-" || value == "/" || value == "*"` can be use just `allOperations.any(operation=> operation=== value)`
> * be accurate with the chain of if's conditions [line 86-102](https://github.com/lzanchin/odin-calculator/blob/main/script.js#L86-102). More details [here](https://stackoverflow.com/questions/43934388/how-to-make-javascript-exclude-some-mentioned-variables)
> * [PRO] the app perfomance is sensitive to number of listeners and every developer should follow the rule: 'the less listeners, the better perfomance'. On [line L9-L13](https://github.com/lzanchin/odin-calculator/blob/main/script.js#L9-L13) the code can be enchanced in [bubbling way](https://javascript.info/bubbling-and-capturing) 🎈 which implies to add one listener on the parent element instead of plenty listeners on each of child.

All changes done. ✅

**Comment by lzanchin** [comment]
> And as a bug, I would mention this behavior: The operation sign is still displayed even the result is computed (see screenshot). Steps to reproduce: `14` `-` `3` `=` output: `11-`
> 
> <img alt="Screen Shot 2023-02-27 at 9 44 06 am" width="420" src="https://user-images.githubusercontent.com/10515741/221445094-1cf67ad0-149b-4ce7-bc10-0735b2400573.png">
> 
> Expect: The operation sign shouldn't be displayed at the end after computing `14` `-` `3` `=` output: `11`

Issues should be fixed now.
